version: "3.9"

services:
  api:
    image: harlus-server
    container_name: api
    expose:
      - "8000"

  nginx:
    image: harlus-nginx
    container_name: nginx
    ports:
      - "8000:443"
    depends_on:
      - api
