# Document Processing Configuration

# Claim Getter
claim getter:
  model_name: "gpt-4o"
  temperature: 0.
  max_tokens: 500

# Claim checker
claim checker:
  question model:
    model_name: "gpt-4o-mini"
    temperature: 0.
    max_tokens: 500
    
  answer model:
    model_name: "gpt-3.5-turbo"
    temperature: 0.
    max_tokens: 250
    
  verification model:
    model_name: "gpt-4o"
    temperature: 0.
    max_tokens: 500