from enum import Enum


class SyncStatus(Enum):
    SYNC_COMPLETE = "SYNC_COMPLETE"
    SYNC_INCOMPLETE = "SYNC_INCOMPLETE"
    SYNC_IN_PROGRESS = "SYNC_IN_PROGRESS"
    SYNC_PENDING = "SYNC_PENDING"
    SYNC_ERROR = "SYNC_ERROR"
    SYNC_PARTIAL_SUCCESS = "SYNC_PARTIAL_SUCCESS"
    SYNC_NOT_STARTED = "SYNC_NOT_STARTED"
    UNTRACKED = "UNTRACKED"
